services:
  five-thirty-app:
    build: .
    container_name: five-thirty-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_TYPE: postgres
      DB_HOST: five-thirty-postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: five-thirty
      DATA_DIR: /data
    volumes:
      - app-data:/data
    ports:
      - '3000:3000'
    depends_on:
      - five-thirty-postgres
    networks:
      - default

  five-thirty-postgres:
    image: postgres:latest
    container_name: five-thirty-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: five-thirty
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  app-data:
  postgres-data:

networks:
  default:
