services:
  five-thirty-app:
    build: .
    container_name: five-thirty-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: five-thirty-postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: five_thirty
      DATA_DIR: /data
      NODE_ENV: production
    volumes:
      - ./data:/data
    depends_on:
      - five-thirty-postgres
    networks:
      - default

  five-thirty-postgres:
    image: postgres:latest
    container_name: five-thirty-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: five_thirty
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres-data:

networks:
  default:
